# Generated by Django 5.2 on 2025-05-22 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, 'Graduate')])),
                ('study_style', models.CharField(choices=[('quiet', 'Quiet'), ('discussion', 'Discussion'), ('flashcards', 'Flashcards'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('prefers_group', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(through='network.UserCourse', to='network.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.userprofile'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('study_style', models.CharField(choices=[('quiet', 'Quiet'), ('discussion', 'Discussion'), ('flashcards', 'Flashcards'), ('mixed', 'Mixed')], max_length=20)),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_one', to='network.userprofile')),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to='network.userprofile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.userprofile')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user_profile', 'course')},
        ),
        migrations.CreateModel(
            name='StudyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_start', models.DateTimeField(blank=True, null=True)),
                ('selected_end', models.DateTimeField(blank=True, null=True)),
                ('invite_message', models.TextField(blank=True, default='Hello! I want to invite you to study with me.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='network.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='network.userprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
