# Generated by Django 5.2 on 2025-05-24 09:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')]), blank=True, default=list, help_text="Select the days you're available to study on.", max_length=50, size=None),
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
