# Generated by Django 5.2 on 2025-05-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_userprofile_prefers_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='participant_one',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='participant_two',
        ),
        migrations.CreateModel(
            name='StudyBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_one', to='network.userprofile')),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to='network.userprofile')),
            ],
            options={
                'unique_together': {('participant_one', 'participant_two')},
            },
        ),
        migrations.CreateModel(
            name='StudyBuddyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_message', models.TextField(blank=True, default='Hello! I want to invite you to study with me.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='network.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='network.userprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.DeleteModel(
            name='StudyInvite',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
